[package]
name = "bls-ed25519-on-gkr"
version = "0.1.0"
edition = "2021"

[dependencies]
expander_compiler = { path = "../ExpanderCompilerCollection/expander_compiler" }
circuit-std-rs = { path = "../ExpanderCompilerCollection/circuit-std-rs" }
num-bigint = "0.4.6"
num-traits = "0.2.19"